RailsXServer/config/routes.rb
RailsXServer::Application.routes.draw do
  resources :screens

  root to:'index#index'
  match 'doc/howto', to:'index#howto',as:'doc_howto'
  match 'doc/team', to:'index#team',as:'doc_team'
  match 'screen_notify/:url', to:'screens#notify'
  match 'screens/notify/:url', to:'screens#notify'
  match 'screens/authenticate/:url',to:'screens#authenticate'
  match 'screens/post/:url', to:'screens#post',via:'post'
  match 'screens/status/:url(/:key)',to:'screens#status'
  match 'screens/thumbnail/:url',to:'screens#thumbnail'

  match 'screens.:format',to:'screens#index'

  match 'embed/:url', to:'screens#show_embed'
  match 'screens/post/:room/:id', to:'screens#post', via:'post'
  match 'screens/show/:url', to:'screens#show'
  match 'private/:url', to: 'screens#show_private'

  match 'users/authenticate/:url', to:'users#authenticate'
  match 'screens/authenticate', to:'users#authenticate'
  match 'users/sign_in', to:'users#sign_in'
  match 'users/sign_up', to:'users#sign_up'
  match 'users/sign_out', to:'users#sign_out', via:'delete'
  match 'users/index', to:'users#index'
  match 'users/edit', to:'users#edit'
  match 'users/update', to:'users#update', via:'post'
#  match 'users/create_screen', to:'users#create_screen', via:'post'
#  match 'users/destroy_screen', to:'users#destroy_screen', via:'post'
  match 'users/update_screen', to:'users#update_screen', via:'post'
  match 'users/show/:name', to:'users#show'

  match 'oauth/switch',to:'oauth#switch', via:'post'
  match 'oauth/disconnect', to:'oauth#disconnect', via:'post'
  match 'auth/:provider/popup' => 'oauth#auth_popup'
  match 'oauth/:provider/popup' => 'oauth#auth_popup'
  match 'oauth/:provider/redirect' => 'oauth#auth_normal'
  match 'oauth/:provider/callback' => 'oauth#callback'
  match 'auth/:provider/callback' => 'oauth#callback'

  match ':url', to:'screens#show'

end

RailsXServer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset='utf-8'>
  <title><%=title%></title>
  <meta content="http://screenx.tv/" property="og:url"/>
  <link rel="canonical" href="http://screenx.tv/"/>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render partial:'/analytics' %>
  <script>csrf_token="<%= form_authenticity_token %>"</script>
</head>
<body>
<header>
  <nobr class='left'>
    <a href='/' class='menu_item'>
      <img src='/assets/logo.png' style='position:absolute;z-index:65536;height:40px;'>
    </a>
  </nobr>
  <nobr class='right'>

    <div class='twitter' style='float:left;margin:4px 4px 0 0;width:100px;height:36px;'>
      <iframe allowtransparency="true" frameborder="0" scrolling="no" src="http://platform.twitter.com/widgets/tweet_button.html" style="width:100px; height:20px;"></iframe>
    </div>
      <script>(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="//connect.facebook.net/en_US/all.js#xfbml=1";fjs.parentNode.insertBefore(js,fjs);}(document,'script','facebook-jssdk'));</script>
    <div style='float:left;margin:4px 4px 0 0;width:100px;height:36px;'>
      <div class="fb-like facebook" data-send="false" data-layout="button_count" data-width="100" data-show-faces="false"></div>
    </div>

    <% if user_signed_in? %>
      <div class='menu_item pulldown'>
        <a class='pulldown-menu' style='padding-left:30px;'>
          <%= image_tag 'menu.png', width: 30, height: 30, style: 'position:absolute;left:0;top:5px' %>
          <%= current_user.nickname %>
        </a>
        <div class='pulldown-target'>
          <div style='padding:5px 20px'>
            <%= link_to 'Account', users_index_path %>
          </div>
          <div style='padding:5px 20px'><%= link_to 'Sign out', users_sign_out_path, method: 'delete' %></div>
        </div>
      </div>
    <% else %>
      <div class='menu_item link'>
        <%= link_to 'Sign up', users_sign_up_path %>
      </div>
      <div class='menu_item pulldown'>
        <%= link_to 'Sign in', users_sign_in_path, class: 'pulldown-menu' %>
        <div class='pulldown-target'>
          <%= form_tag users_sign_in_path, class: 'clearfix' do |f|%>
            <div><%= text_field :sign_in, :name_or_email, placeholder: 'username or email', value: params[:sign_in].try(:[], :name_or_email) %></div>
            <div><%= text_field :sign_in, :password, placeholder:'password', type:'password' %></div>
            <%= submit_tag 'Sign in', class: ['right', 'sign_in_button'] %>
          <% end %>
          <div>
            <div>Sign in with</div>
            <%= link_to oauth_login_path(:twitter), style: 'margin:0 5px' do %>
              <i class='icon-twitter-sign'></i>twitter
            <% end %>
            <%= link_to oauth_login_path(:facebook), style: 'margin:0 5px' do %>
              <i class='icon-facebook-sign'></i>facebook
            <% end %>
          </div>
        </div>
      </div>

    <% end %>
  </nobr>
</header>

<%= yield %>

<footer>
  <div class='left'>©2013 Tomoya Ishida and Yohei Yasukawa</div>
  <div class='right'>
    <span><a href="https://github.com/screenxtv">GitHub</a></span>
    <span><a href='mailto:team@yasulab.jp'>Contact us</a></span>
    <span><a href='/doc/team'>Team</a></span>
    <span><a href='http://blog.screenx.tv'>Blog</a></span>
    <span><a href='http://twitter.com/screenxtv'>Twitter</a></span>
  </div>
</footer>