RailsXServer/config/routes.rb
RailsXServer::Application.routes.draw do
  resources :screens

  root to:'index#index'
  match 'doc/howto', to:'index#howto',as:'doc_howto'
  match 'doc/team', to:'index#team',as:'doc_team'
  match 'screen_notify/:url', to:'screens#notify'
  match 'screens/notify/:url', to:'screens#notify'
  match 'screens/authenticate/:url',to:'screens#authenticate'
  match 'screens/post/:url', to:'screens#post',via:'post'
  match 'screens/status/:url(/:key)',to:'screens#status'
  match 'screens/thumbnail/:url',to:'screens#thumbnail'

  match 'screens.:format',to:'screens#index'

  match 'embed/:url', to:'screens#show_embed'
  match 'screens/post/:room/:id', to:'screens#post', via:'post'
  match 'screens/show/:url', to:'screens#show'
  match 'private/:url', to: 'screens#show_private'

  match 'users/authenticate/:url', to:'users#authenticate'
  match 'screens/authenticate', to:'users#authenticate'
  match 'users/sign_in', to:'users#sign_in'
  match 'users/sign_up', to:'users#sign_up'
  match 'users/sign_out', to:'users#sign_out', via:'delete'
  match 'users/index', to:'users#index'
  match 'users/edit', to:'users#edit'
  match 'users/update', to:'users#update', via:'post'
#  match 'users/create_screen', to:'users#create_screen', via:'post'
#  match 'users/destroy_screen', to:'users#destroy_screen', via:'post'
  match 'users/update_screen', to:'users#update_screen', via:'post'
  match 'users/show/:name', to:'users#show'

  match 'oauth/switch',to:'oauth#switch', via:'post'
  match 'oauth/disconnect', to:'oauth#disconnect', via:'post'
  match 'auth/:provider/popup' => 'oauth#auth_popup'
  match 'oauth/:provider/popup' => 'oauth#auth_popup'
  match 'oauth/:provider/redirect' => 'oauth#auth_normal'
  match 'oauth/:provider/callback' => 'oauth#callback'
  match 'auth/:provider/callback' => 'oauth#callback'

  match ':url', to:'screens#show'

end

RailsXServer/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :display_name, :email, :password, :icon
  attr_accessor :password
  has_many :screens, dependent: :destroy
  has_many :oauths, dependent: :destroy
  validates :name, length: {minimum: 4, maximum: 16}, uniqueness: true, format: /^[_a-zA-Z0-9]*$/
  validates :email, uniqueness: true, format: /^[a-zA-Z0-9_-][a-zA-Z0-9\._-]*@[a-zA-Z0-9_-][a-zA-Z0-9\._-]*$/
  validates_presence_of :password_digest

  before_validation do
    self.screens.new url: self.name if id.nil?
  end

  def self.digest password
    Digest::SHA2.hexdigest password
  end

  def self.find_by_oauth oauth
    Oauth.where(provider: oauth[:provider], uid: oauth[:uid]).first.try :user
  end

  def self.find_by_password name_or_email, password
    if name_or_email&&password
      pswd=digest(password)
      if name_or_email.include? '@'
        User.where(email: name_or_email, password_digest: pswd).first
      else
        User.where(name: name_or_email, password_digest: pswd).first
      end
    end
  end

  def check_password password
    password_digest == User.digest(password)
  end

  def password= password
    if password.try :match, /^[\x21-\x7e]{4,}$/
      self.password_digest = User.digest password
    else
      self.password_digest = nil
    end
    self.auth_key = User.digest "#{self.name}#{self.password}#{rand}"
  end

  def oauth_connect oauth_info
    oauth = oauths.where(provider: oauth_info[:provider]).first_or_initialize
    oauth.update_attributes oauth_info
    self.display_name = oauth.display_name if self.display_name.blank?
    self.icon ||= oauth.icon
    save
  end

  def oauth_disconnect provider
    oauths.where(provider: provider).destroy_all
  end

  def nickname
    display_name.presence || name
  end

  def user_icon
    icon || "/assets/icon/#{id % 32}.png"
  end

end

RailsXServer/app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery except: [:authenticate]
  before_filter :nodejs_filter, only: [:authenticate]
  before_filter :user_signed_in!, except: [:authenticate, :sign_in, :sign_up, :show]
  before_filter :already_signed_in!, only: [:sign_in, :sign_up]

  def authenticate
    user=User.where(name: params[:user]).first
    if user && user.check_password(params[:password])
      render json: {auth_key: user.auth_key}
    else
      render json: {error: 'wrong user or password'}
    end
  end

  def sign_in
    render and return unless request.post?
    if params[:sign_in]
      user = User.find_by_password params[:sign_in][:name_or_email], params[:sign_in][:password]
    end
    if user
      connect_and_build_user_session user
      redirect_to action: :index
    else
      @sign_in_error = 'wrong username, email or password'
    end
  end

  def sign_up
    render 'sign_in' and return unless request.post?
    user=User.new params[:sign_up]
    if user.save
      connect_and_build_user_session user
      redirect_to action: :index
    else
      @sign_up_user = user
      @sign_up_errors = user.errors
      if [:name, :email, :password_digest].all?{|key|@sign_up_errors[key].empty?}
        @reserve_error = true
      end
      render 'sign_in'
    end
  end

  def sign_out
    destroy_user_session
    redirect_to root_path
  end

  def index
  end

  def update
    current_user.display_name = params[:display_name] if params[:display_name]
    current_user.email = params[:email] if params[:email]
    social = social_info[params[:social_icon]]
    current_user.icon = social[:icon] if social
    flash[:notice] = current_user.errors.full_messages.join "<br>" unless current_user.save
    redirect_to action: :index
  end

  # def create_screen
  #   if current_user.screens.count < Screen::USER_MAX_SCREENS
  #     current_user.screens << Screen.new(url:params[:url]);
  #     current_user.save
  #   end
  #   redirect_to users_index_path
  # end

  def update_screen
    screen = current_user.screens.where(url:params[:url]).first
    screen.update_attributes(hash_tag:params[:hash_tag]) if screen
    redirect_to users_index_path
  end

  # def destroy_screen
  #   if params[:url_confirm]==params[:url]
  #     screen = current_user.screens.where(url:params[:url]).first
  #     screen.destroy if screen
  #   end
  #   redirect_to users_index_path
  # end

  def show
    @user = User.where(name: params[:name]).first
    render_404 unless @user
  end

end

RailsXServer/app/helpers/user_helper.rb
module UserHelper
end

RailsXServer/app/helpers/users_helper.rb
module UsersHelper
end

RailsXServer/app/views/users/index.html.erb
<style>
div.main{
	margin:5px 20px;
	font-size:18px;
}
div.item{
	box-shadow:0 0 8px silver;
	margin:16px;
	padding:4px;
}
div.item div{font-size:18px;}
div.item div.url{font-size:24px;}
</style>
<div class='main'>
	<%= form_tag users_update_path do %>
		<h1>
			<%= image_tag current_user.user_icon %>
			<%= current_user.name %>
		</h1>
		<div>display name: <input type=text name='display_name' value="<%= current_user.display_name %>"></div>
		<div>email: <input type=text  name='email' value="<%= current_user.email %>"></div>
		<div>
			<% is_anonymous = current_user.user_icon == social_info['anonymous'][:icon] %>
			<input type=radio name='social_icon' value='anonymous' <%= 'checked' if is_anonymous %>>
			<%= image_tag social_info['anonymous'][:icon], width: 24, height: 24 %>use default icon
		</div>
		<% current_user.oauths.each do |oauth| %>
			<div>
				<input type=radio name='social_icon' value=<%= oauth.provider %> <%= 'checked' if oauth.icon == current_user.icon %>>
				<%= image_tag oauth.icon, width: 24, height: 24 %>use <%= oauth.provider %> icon
			</div>
		<% end %>
		<div style='color:red'><%= flash[:notice] %></div>
		<input type=submit value=save>
	<% end %>
		<br><br>
		<div class='socials'>
			<% OAuthConsumers.keys.each do |provider| %>
				<% social = social_info[provider] %>
				<div>
					<% if social %>
						<b><%= provider %></b>
						<%= image_tag social[:icon], width: 24, height: 24 %>
						<%= social[:display_name] %>
						<%= link_to 'disconnect', oauth_disconnect_path(provider: provider), method: :post %>
					<% else %>
						<b><%= provider %></b><%= link_to 'connect',oauth_login_path(provider) %>
					<% end %>
				</div>
			<% end %>
		</div>
	<br>
	<h1>Reserved URLs</h1>
	<% screens = current_user.screens %>
	<% screens.each do |screen| %>
		<div class='item'>
			<%= form_tag users_update_screen_path do %>
				<div class='url'><a href="/<%= screen.url %>"><%= screen.url %></a></div>
				
				<input type=hidden name=url value="<%= screen.url %>">
				hash tag:<input type=text name='hash_tag' autocomplete=off placeholder='#hashtag' value='<%= screen.hash_tag%>'>

				<div>Total Viewer: <%= screen.total_viewer %></div>
				<div>Max Viewer: <%= screen.max_viewer %></div>
				<div>Cast Count: <%= screen.cast_count %></div>
				<% time=screen.total_time %>
				<div>Total Time: <%= time/60/60/24 %>days <%= h=time/60/60%24;"#{h/10}#{h%10}"%>:<%= m=time/60%60;"#{m/10}#{m%10}" %></div>
				<input type=submit value=save>
			<% end %>
		</div>
	<% end %>
	<% if false && screens.size < Screen::USER_MAX_SCREENS %>
		<%= form_tag users_create_screen_path do %>
			<input name=url autocomplete=off placeholder='url'>
			<input type=submit value='create'>
		<% end %>
	<% end %>
</div>

RailsXServer/app/views/users/show.html.erb
<style>
div.main{
	margin:5px 20px;
	font-size:18px;
}
#sign_in,#sign_up{
	margin:16px;
	border-radius:8px;
	background:white;
	box-shadow:0 0 8px silver;
	width:300px;
}
div.item{
	box-shadow:0 0 8px silver;
	margin:16px;
	padding:4px;
}
div.item div{font-size:18px;}
div.item div.url{font-size:24px;}
</style>
<div class='main' style='margin-left:auto;margin-right:auto;width:900px;'>
	<h1>
		<%= image_tag @user.user_icon, width: 48, height: 48 %>
		<%= @user.name %>
	</h1>
	<div>
		<b><%= @user.display_name %></b>
		<% @user.oauths.each do |oauth| %>
			
			<a href="<%= oauth.url %>" target='_blank' class='icon-<%= oauth.provider %>' style='color:white;background:gray;text-decoration:none;padding:5px;display:inline-block;border-radius:4px;width:18px;height:18px;text-align:center;'></a>
			
		<% end %>
	</div>
	<%= link_to 'edit profile', users_index_path, class:'icon-edit' if @user == current_user %>
	<br>
	<h1>Reserved URLs</h1>
	<div class='clearfix'>
		<% @user.screens.each do |screen| %>
			<div class='item' style='float:left;width:400px;'>
				<div class='url'><a href="/<%= screen.url %>"><%= screen.url %></a></div>
				<div>Total Viewer: <%= screen.total_viewer %></div>
				<div>Max Viewer: <%= screen.max_viewer %></div>
				<% time=screen.total_time %>
				<div>Total Time: <%= time/60/60/24 %>days <%= h=time/60/60%24;"#{h/10}#{h%10}"%>:<%= m=time/60%60;"#{m/10}#{m%10}" %></div>
			</div>
		<% end %>
	</div>
</div>

RailsXServer/app/views/users/sign_in.html.erb
<style>
div.main{
  width:700px;
  margin:20px;
  text-align:left;
  padding:5px 20px;
}
</style>
<center>
<div class='main'>
	<% OAuthConsumers.keys.each do |provider| %>
		<% info = social_info[provider] %>
		<% if info %>
			<% @show_message = true %>
			<div>
				<b><%= provider %></b>
				<%= image_tag info[:icon], width: 24, height: 24 %>
				<%= info[:display_name] %>
			</div>
		<% end %>
	<% end %>
	<% if @show_message %>
		<div>please fill in the information below.</div>
	<% end %>
	<%= form_tag users_sign_in_path, id: 'sign_in' do |f| %>
		<div class='sign_head'>Sign in</div>
		<%= text_field :sign_in, :name_or_email, placeholder: 'username or email', value: params[:sign_in].try(:[], :name_or_email) %>
		<%= text_field :sign_in, :password, placeholder: 'password', type: 'password' %>
		<div class='error'><%= @sign_in_error %></div>
		<%= submit_tag 'Sign in',class: 'sign_in_button' %>
	<% end %>
	<%= form_tag users_sign_up_path, id: 'sign_up' do |f|%>
		<div class='sign_head'>Create your account</div>
		<%= text_field :sign_up, :name, placeholder: 'username', autocomplete: 'off', value:@sign_up_user.try(:name) %>
		<% @sign_up_errors.try(:[], :name).try(:each) do |error| %>
			<div class='error'>username <%= error %></div>
		<% end %>
		<%= text_field :sign_up, :email, placeholder: 'email', autocomplete: 'off', value:@sign_up_user.try(:email) %>
		<% @sign_up_errors.try(:[], :email).try(:each) do |error| %>
			<div class='error'>email <%= error %></div>
		<% end %>
		<%= text_field :sign_up, :password, type: 'password', placeholder: 'password', autocomplete: 'off', value: '' %>
		<% if @sign_up_errors.try(:[], :password_digest).present? %>
			<div class='error'>password invalid</div>
		<% end %>
		<% if @reserve_error %>
			<div class='error'><%= "cannot reserve url: #{@sign_up_user.name}" %></div>
		<% end %>
		<%= submit_tag 'Create account',class: 'sign_up_button' %>
	<% end %>
	<div style='clear:left;'></div>
	<div style='font-size:18px;'>
		If you create your account:
		<ul>
			<li>
			  You can get a reserved url
			  (e.g. if your username is 'tompng', you'll get 'http://screenx.tv/tompng').
			</li>
			<li>
			  Chat logs in your broadcasting page are stored and not flushed.
			</li>
		</ul>
	</div>
</center>